
package jaxws.attachment.server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.adapters.HexBinaryAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.ws.Holder;
import javax.activation.DataHandler;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI IBM 2.0_03-06/12/2007 07:44 PM(Raja)-fcs
 * Generated source version: 2.0
 * 
 */
@WebService(name = "CheckAttachmentPortType", targetNamespace = "http://server.attachment.jaxws")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CheckAttachmentPortType {


    /**
     * 
     * @param mimeAttachment
     * @param request
     * @param response
     */
    @WebMethod
    public void retrieve(
        @WebParam(name = "request", targetNamespace = "http://server.attachment.jaxws", partName = "request")
        String request,
        @WebParam(name = "response", targetNamespace = "http://server.attachment.jaxws", mode = WebParam.Mode.OUT, partName = "response")
        Holder<String> response,
        @XmlJavaTypeAdapter(HexBinaryAdapter.class)
        @WebParam(name = "mimeAttachment", targetNamespace = "http://server.attachment.jaxws", mode = WebParam.Mode.OUT, partName = "mimeAttachment")
        Holder<DataHandler> mimeAttachment);

}
