
package jaxws.attachment.server;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI IBM 2.0_03-06/12/2007 07:44 PM(Raja)-fcs
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "CheckAttachmentService", targetNamespace = "http://server.attachment.jaxws", wsdlLocation = "C:\\prebuild\\WFVT\\ws\\code\\websvcs.fvt\\src\\jaxws\\attachment\\etc\\CheckAttachmentService.wsdl")
public class CheckAttachmentService
    extends Service
{

    private final static URL CHECKATTACHMENTSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("file:/C:/prebuild/WautoFVT/src/jaxws/attachment/etc/checkAttachmentService.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        CHECKATTACHMENTSERVICE_WSDL_LOCATION = url;
    }

    public CheckAttachmentService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CheckAttachmentService() {
        super(CHECKATTACHMENTSERVICE_WSDL_LOCATION, new QName("http://server.attachment.jaxws", "CheckAttachmentService"));
    }

    /**
     * 
     * @return
     *     returns CheckAttachmentPortType
     */
    @WebEndpoint(name = "CheckAttachmentServicePort")
    public CheckAttachmentPortType getCheckAttachmentServicePort() {
        return (CheckAttachmentPortType)super.getPort(new QName("http://server.nullattachment.jaxws", "CheckAttachmentServicePort"), CheckAttachmentPortType.class);
    }

}
