package common.utils.topology;

public enum Ports {

    // Generic ports
    BOOTSTRAP_ADDRESS ("BOOTSTRAP_ADDRESS"),
    CSIV2_SSL_MUTUALAUTH_LISTENER_ADDRESS ("CSIV2_SSL_MUTUALAUTH_LISTENER_ADDRESS"),
    CSIV2_SSL_SERVERAUTH_LISTENER_ADDRESS ("CSIV2_SSL_SERVERAUTH_LISTENER_ADDRESS"),
    DCS_UNICAST_ADDRESS ("DCS_UNICAST_ADDRESS"),
    ORB_LISTENER_ADDRESS ("ORB_LISTENER_ADDRESS"),
    ORB_SSL_LISTENER_ADDRESS ("ORB_SSL_LISTENER_ADDRESS"),
    SAS_SSL_SERVERAUTH_LISTENER_ADDRESS ("SAS_SSL_SERVERAUTH_LISTENER_ADDRESS"),
    SOAP_CONNECTOR_ADDRESS ("SOAP_CONNECTOR_ADDRESS"),
    WC_adminhost ("WC_adminhost"),
    WC_adminhost_secure ("WC_adminhost_secure"),
    IPC_CONNECTOR_ADDRESS ("IPC_CONNECTOR_ADDRESS"),
    OVERLAY_UDP_LISTENER_ADDRESS("OVERLAY_UDP_LISTENER_ADDRESS"),
    OVERLAY_TCP_LISTENER_ADDRESS("OVERLAY_TCP_LISTENER_ADDRESS"),

    // App Server ports
    CUSTOM_CFW_HTTP_PORT ("CUSTOM_CFW_HTTP_PORT"),
    CUSTOM_CFW_HTTPS_PORT ("CUSTOM_CFW_HTTPS_PORT"),
    SIB_ENDPOINT_ADDRESS ("SIB_ENDPOINT_ADDRESS"),
    SIB_ENDPOINT_SECURE_ADDRESS ("SIB_ENDPOINT_SECURE_ADDRESS"),
    SIB_MQ_ENDPOINT_ADDRESS ("SIB_MQ_ENDPOINT_ADDRESS"),
    SIB_MQ_ENDPOINT_SECURE_ADDRESS ("SIB_MQ_ENDPOINT_SECURE_ADDRESS"),
    SIP_DEFAULTHOST ("SIP_DEFAULTHOST"),
    SIP_DEFAULTHOST_SECURE ("SIP_DEFAULTHOST_SECURE"),
    WC_defaulthost ("WC_defaulthost"),
    WC_defaulthost_secure ("WC_defaulthost_secure"),
    
    // Node ports
    DRS_CLIENT_ADDRESS ("DRS_CLIENT_ADDRESS"),
    NODE_DISCOVERY_ADDRESS ("NODE_DISCOVERY_ADDRESS"),
    NODE_IPV6_MULTICAST_DISCOVERY_ADDRESS ("NODE_IPV6_MULTICAST_DISCOVERY_ADDRESS"),
    NODE_MULTICAST_DISCOVERY_ADDRESS ("NODE_MULTICAST_DISCOVERY_ADDRESS"),
    
    // Dmgr ports
    CELL_DISCOVERY_ADDRESS ("CELL_DISCOVERY_ADDRESS"),
    DataPowerMgr_inbound_secure("DataPowerMgr_inbound_secure"),
    
    // Admin agent ports
    RMI_CONNECTOR_ADDRESS("RMI_CONNECTOR_ADDRESS"),
    JSR160RMI_CONNECTOR_ADDRESS("JSR160RMI_CONNECTOR_ADDRESS"),
    
    // Web Server ports
    WEBSERVER_ADDRESS("WEBSERVER_ADDRESS"),
    WEBSERVER_ADMIN_ADDRESS("WEBSERVER_ADMIN_ADDRESS"),
    
    // for liberty new-added
    OSGi("OSGi"),
    HTTP("HTTP"),
    HTTP_SECURE("HTTP_SECURE"),
    IIOP("HTTP_SECURE"),
    JMX_REST("HTTP_SECURE");

    private final String portName;
    private Ports(String portName) {
        this.portName = portName;
    }
    
    /**
     * Returns the port name used in the property file for this Port
     * 
     * @return The port name used in the property file for this Port
     */
    public String getPortName() {
        return this.portName;
    }
}
