<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<definitions 
	targetNamespace="http://server.jaxwstooling.annotations/" 
	name="AddNumbersImplService" 
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
	xmlns:tns="http://server.jaxwstooling.annotations/" 
	xmlns="http://schemas.xmlsoap.org/wsdl/">
  <types>
    <xsd:schema>
      <xsd:import namespace="http://server.jaxwstooling.annotations/" schemaLocation="JaxwsToolingService_schema1.xsd"/>
    </xsd:schema>
  </types>
  <message name="addTwoNumbers">
    <part name="parameters" element="tns:addTwoNumbers"/>
  </message>
  <message name="addTwoNumbersResponse">
    <part name="parameters" element="tns:addTwoNumbersResponse"/>
  </message>
  <message name="AddNegativeNumbersException">
    <part name="fault" element="tns:AddNegativeNumbersException"/>
  </message>
  <portType name="AddNumbersImpl">
    <operation name="addTwoNumbers">
      <input message="tns:addTwoNumbers"/>
      <output message="tns:addTwoNumbersResponse"/>
      <fault name="AddNegativeNumbersException" message="tns:AddNegativeNumbersException"/>
    </operation>
  </portType>
  <binding name="AddNumbersImplPortBinding" type="tns:AddNumbersImpl">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
    <operation name="addTwoNumbers">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
      <fault name="AddNegativeNumbersException">
        <soap:fault name="AddNegativeNumbersException" use="literal"/>
      </fault>
    </operation>
  </binding>
  <service name="AddNumbersImplService">
    <port name="AddNumbersImplPort" binding="tns:AddNumbersImplPortBinding">
      <soap:address location="http://@REPLACE_WITH_HOST_NAME@:@REPLACE_WITH_PORT_NUM@/addnumbers/addnumbers"/>
    </port>
  </service>
</definitions>

