<?xml version="1.0" encoding="UTF-8"?>
<definitions name="AddNumbersImplPartial2Service" 
	targetNamespace="http://serverpartial2.partialwsdl.annotations/" 
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
	xmlns:tns="http://serverpartial2.partialwsdl.annotations/" 
	xmlns="http://schemas.xmlsoap.org/wsdl/">
  <types>
    <xsd:schema>
      <xsd:import namespace="http://serverpartial2.partialwsdl.annotations/" schemaLocation="AddNumbersImplPartial2Service_schema1.xsd"/>
    </xsd:schema>
  </types>
  <message name="addTwoNumbersResponse">
    <part name="parameters" element="tns:addTwoNumbersResponse">
    </part>
  </message>
  <message name="addTwoNumbers">
    <part name="parameters" element="tns:addTwoNumbers">
    </part>
  </message>
  <portType name="AddNumbersImplPartial2">
    <operation name="addTwoNumbers">
      <input message="tns:addTwoNumbers">
    </input>
      <output message="tns:addTwoNumbersResponse">
    </output>
    </operation>
  </portType>
  <binding name="AddNumbersImplPartial2PortBinding" type="tns:AddNumbersImplPartial2">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="addTwoNumbers">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="AddNumbersImplPartial2Service">
    <port name="AddNumbersImplPartial2Port" binding="tns:AddNumbersImplPartial2PortBinding">
      <soap:address location="http://@REPLACE_WITH_HOST_NAME@:@REPLACE_WITH_PORT_NUM@/partialwsdlp2/services/AddNumbersImplPartial2Service"/>
    </port>
  </service>
</definitions>
