/*
 * @(#) 1.2 autoFVT/src/annotations/webmethod_g2/runtime_beta/server/InterfaceTestIf.java, WAS.websvcs.fvt, WAS85.FVT, cf011231.01 1/5/07 14:50:47 [8/8/12 06:55:34]
 *
 *
 * IBM Confidential OCO Source Material
 * 5724-J08 (C) COPYRIGHT International Business Machines Corp. 2003, 2005
 * The source code for this program is not published or otherwise divested
 * of its trade secrets, irrespective of what has been deposited with the
 * U.S. Copyright Office.
 *
 * Change History:
 * Date        UserId      Feature/Defect     Description
 * -----------------------------------------------------------------------------
 * 9/20/06     btiffany    LIDB3296.31.01     new file
 *
 */
// Due to a beta limitation, this file has to be replaced with 
// a fully qualified SEI generated by wsimport.
// However, we need it to generate wsdl in the first place.

package annotations.webmethod_g2.runtime_beta.server;
import javax.jws.*;

// oops, interfaceTest got picked up by junit, so renamed to 
// InterfaceTestIf, and used annotation to keep wsdl the same.
@WebService(	
			wsdlLocation="WEB-INF/wsdl/doesntmatter.wsdl",
            name="InterfaceTest"
			)
//@WebResult needed due to beta limitation, may go away later.
public interface InterfaceTestIf {
    
    // one method has @WebMethod anno, one doesn't, both should work. 

   
    @WebResult(name="notreturn")
	public String methodOne(String s);
	
	@WebMethod()
    @WebResult(name="notreturn")
	public String  methodTwo(String s);
    
    // totally unrelated..
    @WebResult(name="notreturn")
    @WebMethod
    public String mixTypes(String s, boolean b, Double d, int i, float f, int c);
}
