//
// @(#) 1.1 autoFVT/src/jaxws/badproxy/wsfvt/server/NoWsdlSOAP12BadPortImpl.java, WAS.websvcs.fvt, WAS85.FVT, cf011231.01 9/27/06 09:03:43 [8/8/12 06:55:25]
//
// IBM Confidential OCO Source Material
// (C) COPYRIGHT International Business Machines Corp. 2006
// The source code for this program is not published or otherwise divested
// of its trade secrets, irrespective of what has been deposited with the
// U.S. Copyright Office.
//
// Change History:
// Date       UserId      Defect             Description
// ----------------------------------------------------------------------------
// 05/31/06   sedov       LIDB3296.41-02     New File
//

package jaxws.badproxy.wsfvt.server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.ws.BindingType;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * An endpoint without a wsdl or an SEI. Expecting that a wsdl
 * will be auto-generated by the runtime based on the BindingType
 * annotation. The method is fully annotated to force the wsdl to
 * be generated in accordance with pre-made wsdl used to generate
 * the client
 */
@BindingType(value = javax.xml.ws.soap.SOAPBinding.SOAP12HTTP_BINDING)
@WebService(name="NoWsdlSOAP12Port",
		portName="NoWsdlSOAP12Port",
		serviceName="NoWsdlSOAP12Service",
		targetNamespace="http://NoWsdlSOAP12.common.wsfvt.badproxy.jaxws")
public class NoWsdlSOAP12BadPortImpl {

    @WebMethod(action = "http://NoWsdlSOAP12.common.wsfvt.badproxy.jaxws/ping")
    @RequestWrapper(localName = "ping", targetNamespace = "http://common.wsfvt.badproxy.jaxws", className = "jaxws.badproxy.wsfvt.common.Ping")
    @ResponseWrapper(localName = "pingResponse", targetNamespace = "http://common.wsfvt.badproxy.jaxws", className = "jaxws.badproxy.wsfvt.common.PingResponse")
    public void ping(
        @WebParam(name = "ping", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<String> ping){
		
	}

}
