// Due to a beta limitation, this file has to be replaced with 
// a fully qualified SEI generated by wsimport.
// However, we need it to generate wsdl in the first place.
package annotations.webservice_g2.interfaces.server;
import javax.jws.*;


@WebService(name="InterfaceTestTwo",			
			wsdlLocation="WEB-INF/wsdl/doesntmatter.wsdl"  
			)
//@WebResult needed due to beta limitation, may go away later.            
public interface InterfaceTestTwo {	
	
    @WebResult(name="notreturn")
	public String bareIfMethod(String s);
	
	@WebMethod()
    @WebResult(name="notreturn")
	public String annoIfMethod(String s);
	
	// per jsr181 3.2, this method should not map to wsdl if excluded 
	//@WebMethod(exclude=true)
    @WebResult(name="notreturn")
	public String annoIfExcluded(String s);	
	

}
